from github import Github
from config.settings import GITHUB_TOKEN

g = Github(GITHUB_TOKEN)

def push_project(project_name: str, files: dict) -> str:
    user = g.get_user()
    
    try:
        repo = user.get_repo(project_name)
    except:
        repo = user.create_repo(
            project_name,
            description="Generated by Matin Meta Agent",
            private=False,
            auto_init=False
        )
    
    for filename, content in files.items():
        try:
            existing = repo.get_contents(filename)
            repo.update_file(filename, f"Update {filename}", content, existing.sha)
        except:
            repo.create_file(filename, f"Add {filename}", content)
    
    return repo.html_url
